# A base centos image with only openssh-server installed and started
#
# VERSION               0.0.1

FROM     hdsh196.lss.emc.com:5000/stanley:base
MAINTAINER stanley shi

# make sure the package repository is up to date

RUN yum -y install openssh-server
RUN echo 'root:changeme' |chpasswd
RUN service sshd start
RUN service sshd stop
RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config
RUN sed -ri 's/#UsePAM no/UsePAM no/g' /etc/ssh/sshd_config

EXPOSE 22
CMD    /usr/sbin/sshd -D

